# Generated by Django 6.1 on 2026-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertrack',
            name='level',
            field=models.CharField(choices=[('FRESHER', 'Fresher'), ('EXPERIENCED', 'Experienced')], default='FRESHER', max_length=20),
        ),
    ]
